//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsMT.MTProvider.TranslationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tilde.com/", ConfigurationName="TranslationService.TranslationServiceSoap")]
    public interface TranslationServiceSoap {
        
        // CODEGEN: Parameter 'GetSystemListResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tilde.com/GetSystemList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        LetsMT.MTProvider.TranslationService.GetSystemListResponse GetSystemList(LetsMT.MTProvider.TranslationService.GetSystemListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tilde.com/Translate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string Translate(string sourceText, string system);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tilde.com/")]
    public partial class SystemConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Description[] descriptionField;
        
        private string idField;
        
        private string sourceLangField;
        
        private string targetLangField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", Order=0)]
        public Description[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourceLang {
            get {
                return this.sourceLangField;
            }
            set {
                this.sourceLangField = value;
                this.RaisePropertyChanged("sourceLang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetLang {
            get {
                return this.targetLangField;
            }
            set {
                this.targetLangField = value;
                this.RaisePropertyChanged("targetLang");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.tilde.com/")]
    public partial class Description : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSystemList", WrapperNamespace="http://www.tilde.com/", IsWrapped=true)]
    public partial class GetSystemListRequest {
        
        public GetSystemListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSystemListResponse", WrapperNamespace="http://www.tilde.com/", IsWrapped=true)]
    public partial class GetSystemListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tilde.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("System", IsNullable=false)]
        public SystemConfiguration[] GetSystemListResult;
        
        public GetSystemListResponse() {
        }
        
        public GetSystemListResponse(SystemConfiguration[] GetSystemListResult) {
            this.GetSystemListResult = GetSystemListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TranslationServiceSoapChannel : LetsMT.MTProvider.TranslationService.TranslationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TranslationServiceSoapClient : System.ServiceModel.ClientBase<LetsMT.MTProvider.TranslationService.TranslationServiceSoap>, LetsMT.MTProvider.TranslationService.TranslationServiceSoap {
        
        public TranslationServiceSoapClient() {
        }
        
        public TranslationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.TranslationService.GetSystemListResponse LetsMT.MTProvider.TranslationService.TranslationServiceSoap.GetSystemList(LetsMT.MTProvider.TranslationService.GetSystemListRequest request) {
            return base.Channel.GetSystemList(request);
        }
        
        public SystemConfiguration[] GetSystemList() {
            LetsMT.MTProvider.TranslationService.GetSystemListRequest inValue = new LetsMT.MTProvider.TranslationService.GetSystemListRequest();
            LetsMT.MTProvider.TranslationService.GetSystemListResponse retVal = ((LetsMT.MTProvider.TranslationService.TranslationServiceSoap)(this)).GetSystemList(inValue);
            return retVal.GetSystemListResult;
        }
        
        public string Translate(string sourceText, string system) {
            return base.Channel.Translate(sourceText, system);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tilde.com/", ConfigurationName="TranslationService.TranslationServiceHttpGet")]
    public interface TranslationServiceHttpGet {
        
        // CODEGEN: Generating message contract since the operation GetSystemList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tilde.com/TranslationServiceHttpGet/GetSystemListRequest", ReplyAction="http://www.tilde.com/TranslationServiceHttpGet/GetSystemListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        LetsMT.MTProvider.TranslationService.GetSystemListResponse1 GetSystemList(LetsMT.MTProvider.TranslationService.GetSystemListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation Translate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tilde.com/TranslationServiceHttpGet/TranslateRequest", ReplyAction="http://www.tilde.com/TranslationServiceHttpGet/TranslateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        LetsMT.MTProvider.TranslationService.TranslateResponse Translate(LetsMT.MTProvider.TranslationService.TranslateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemListRequest1 {
        
        public GetSystemListRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tilde.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("System", IsNullable=false)]
        public SystemConfiguration[] SystemConfigurations;
        
        public GetSystemListResponse1() {
        }
        
        public GetSystemListResponse1(SystemConfiguration[] SystemConfigurations) {
            this.SystemConfigurations = SystemConfigurations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sourceText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string system;
        
        public TranslateRequest() {
        }
        
        public TranslateRequest(string sourceText, string system) {
            this.sourceText = sourceText;
            this.system = system;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tilde.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public TranslateResponse() {
        }
        
        public TranslateResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TranslationServiceHttpGetChannel : LetsMT.MTProvider.TranslationService.TranslationServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TranslationServiceHttpGetClient : System.ServiceModel.ClientBase<LetsMT.MTProvider.TranslationService.TranslationServiceHttpGet>, LetsMT.MTProvider.TranslationService.TranslationServiceHttpGet {
        
        public TranslationServiceHttpGetClient() {
        }
        
        public TranslationServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslationServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.TranslationService.GetSystemListResponse1 LetsMT.MTProvider.TranslationService.TranslationServiceHttpGet.GetSystemList(LetsMT.MTProvider.TranslationService.GetSystemListRequest1 request) {
            return base.Channel.GetSystemList(request);
        }
        
        public SystemConfiguration[] GetSystemList() {
            LetsMT.MTProvider.TranslationService.GetSystemListRequest1 inValue = new LetsMT.MTProvider.TranslationService.GetSystemListRequest1();
            LetsMT.MTProvider.TranslationService.GetSystemListResponse1 retVal = ((LetsMT.MTProvider.TranslationService.TranslationServiceHttpGet)(this)).GetSystemList(inValue);
            return retVal.SystemConfigurations;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.TranslationService.TranslateResponse LetsMT.MTProvider.TranslationService.TranslationServiceHttpGet.Translate(LetsMT.MTProvider.TranslationService.TranslateRequest request) {
            return base.Channel.Translate(request);
        }
        
        public string Translate(string sourceText, string system) {
            LetsMT.MTProvider.TranslationService.TranslateRequest inValue = new LetsMT.MTProvider.TranslationService.TranslateRequest();
            inValue.sourceText = sourceText;
            inValue.system = system;
            LetsMT.MTProvider.TranslationService.TranslateResponse retVal = ((LetsMT.MTProvider.TranslationService.TranslationServiceHttpGet)(this)).Translate(inValue);
            return retVal.@string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tilde.com/", ConfigurationName="TranslationService.TranslationServiceHttpPost")]
    public interface TranslationServiceHttpPost {
        
        // CODEGEN: Generating message contract since the operation GetSystemList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tilde.com/TranslationServiceHttpPost/GetSystemListRequest", ReplyAction="http://www.tilde.com/TranslationServiceHttpPost/GetSystemListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        LetsMT.MTProvider.TranslationService.GetSystemListResponse2 GetSystemList(LetsMT.MTProvider.TranslationService.GetSystemListRequest2 request);
        
        // CODEGEN: Generating message contract since the operation Translate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tilde.com/TranslationServiceHttpPost/TranslateRequest", ReplyAction="http://www.tilde.com/TranslationServiceHttpPost/TranslateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        LetsMT.MTProvider.TranslationService.TranslateResponse1 Translate(LetsMT.MTProvider.TranslationService.TranslateRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemListRequest2 {
        
        public GetSystemListRequest2() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemListResponse2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tilde.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("System", IsNullable=false)]
        public SystemConfiguration[] SystemConfigurations;
        
        public GetSystemListResponse2() {
        }
        
        public GetSystemListResponse2(SystemConfiguration[] SystemConfigurations) {
            this.SystemConfigurations = SystemConfigurations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sourceText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string system;
        
        public TranslateRequest1() {
        }
        
        public TranslateRequest1(string sourceText, string system) {
            this.sourceText = sourceText;
            this.system = system;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TranslateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.tilde.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public TranslateResponse1() {
        }
        
        public TranslateResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface TranslationServiceHttpPostChannel : LetsMT.MTProvider.TranslationService.TranslationServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TranslationServiceHttpPostClient : System.ServiceModel.ClientBase<LetsMT.MTProvider.TranslationService.TranslationServiceHttpPost>, LetsMT.MTProvider.TranslationService.TranslationServiceHttpPost {
        
        public TranslationServiceHttpPostClient() {
        }
        
        public TranslationServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslationServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.TranslationService.GetSystemListResponse2 LetsMT.MTProvider.TranslationService.TranslationServiceHttpPost.GetSystemList(LetsMT.MTProvider.TranslationService.GetSystemListRequest2 request) {
            return base.Channel.GetSystemList(request);
        }
        
        public SystemConfiguration[] GetSystemList() {
            LetsMT.MTProvider.TranslationService.GetSystemListRequest2 inValue = new LetsMT.MTProvider.TranslationService.GetSystemListRequest2();
            LetsMT.MTProvider.TranslationService.GetSystemListResponse2 retVal = ((LetsMT.MTProvider.TranslationService.TranslationServiceHttpPost)(this)).GetSystemList(inValue);
            return retVal.SystemConfigurations;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.TranslationService.TranslateResponse1 LetsMT.MTProvider.TranslationService.TranslationServiceHttpPost.Translate(LetsMT.MTProvider.TranslationService.TranslateRequest1 request) {
            return base.Channel.Translate(request);
        }
        
        public string Translate(string sourceText, string system) {
            LetsMT.MTProvider.TranslationService.TranslateRequest1 inValue = new LetsMT.MTProvider.TranslationService.TranslateRequest1();
            inValue.sourceText = sourceText;
            inValue.system = system;
            LetsMT.MTProvider.TranslationService.TranslateResponse1 retVal = ((LetsMT.MTProvider.TranslationService.TranslationServiceHttpPost)(this)).Translate(inValue);
            return retVal.@string;
        }
    }
}
