//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsMT.MTProvider.LocalLetsMTWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.letsmt.eu/translationAPI", ConfigurationName="LocalLetsMTWebService.TranslationWebServiceSoap")]
    public interface TranslationWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/Translate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Translate(string appID, string systemID, string text, string options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/TranslateArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TranslateArray(string appID, string systemID, string[] textArray, string options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/DetectLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DetectLanguage(string appID, string text, string[] candidateList);
        
        // CODEGEN: Parameter 'BreakSentencesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/BreakSentences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LetsMT.MTProvider.LocalLetsMTWebService.BreakSentencesResponse BreakSentences(LetsMT.MTProvider.LocalLetsMTWebService.BreakSentencesRequest request);
        
        // CODEGEN: Parameter 'GetSystemListResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/GetSystemList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LetsMT.MTProvider.LocalLetsMTWebService.GetSystemListResponse GetSystemList(LetsMT.MTProvider.LocalLetsMTWebService.GetSystemListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetUserInfo(string appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/UpdateTranslation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UpdateTranslation(string appID, string systemID, string text, string translation, string options);
        
        // CODEGEN: Parameter 'content' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/CreateDocTranslation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LetsMT.MTProvider.LocalLetsMTWebService.CreateDocTranslationResponse CreateDocTranslation(LetsMT.MTProvider.LocalLetsMTWebService.CreateDocTranslationRequest request);
        
        // CODEGEN: Parameter 'GetDocTranslationResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/GetDocTranslation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LetsMT.MTProvider.LocalLetsMTWebService.GetDocTranslationResponse GetDocTranslation(LetsMT.MTProvider.LocalLetsMTWebService.GetDocTranslationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/GetDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetDoc(string docId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/RemoveDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void RemoveDoc(string docID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class SentenceBoundary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int startField;
        
        private int lengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/logic/translator")]
    public partial class MetadataField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class ObjectProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class LangText : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private LangText nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LangText Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class MTSystem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private Language srcLanguageField;
        
        private Language trgLanguageField;
        
        private string domainField;
        
        private LangText titleField;
        
        private LangText descriptionField;
        
        private ObjectProperty[] metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Language SrcLanguage {
            get {
                return this.srcLanguageField;
            }
            set {
                this.srcLanguageField = value;
                this.RaisePropertyChanged("SrcLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Language TrgLanguage {
            get {
                return this.trgLanguageField;
            }
            set {
                this.trgLanguageField = value;
                this.RaisePropertyChanged("TrgLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LangText Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public LangText Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
        public ObjectProperty[] Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BreakSentences", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class BreakSentencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        public string appID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=1)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=2)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=3)]
        public string options;
        
        public BreakSentencesRequest() {
        }
        
        public BreakSentencesRequest(string appID, string language, string text, string options) {
            this.appID = appID;
            this.language = language;
            this.text = text;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BreakSentencesResponse", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class BreakSentencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sentence", IsNullable=false)]
        public LetsMT.MTProvider.LocalLetsMTWebService.SentenceBoundary[] BreakSentencesResult;
        
        public BreakSentencesResponse() {
        }
        
        public BreakSentencesResponse(LetsMT.MTProvider.LocalLetsMTWebService.SentenceBoundary[] BreakSentencesResult) {
            this.BreakSentencesResult = BreakSentencesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSystemList", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class GetSystemListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        public string appID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=1)]
        public string uiLanguageID;
        
        public GetSystemListRequest() {
        }
        
        public GetSystemListRequest(string appID, string uiLanguageID) {
            this.appID = appID;
            this.uiLanguageID = uiLanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSystemListResponse", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class GetSystemListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("System", IsNullable=false)]
        public LetsMT.MTProvider.LocalLetsMTWebService.MTSystem[] GetSystemListResult;
        
        public GetSystemListResponse() {
        }
        
        public GetSystemListResponse(LetsMT.MTProvider.LocalLetsMTWebService.MTSystem[] GetSystemListResult) {
            this.GetSystemListResult = GetSystemListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDocTranslation", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class CreateDocTranslationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=2)]
        public string systemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=3)]
        public bool ignoreWarnings;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=4)]
        public LetsMT.MTProvider.LocalLetsMTWebService.MetadataField[] metadata;
        
        public CreateDocTranslationRequest() {
        }
        
        public CreateDocTranslationRequest(string fileName, byte[] content, string systemID, bool ignoreWarnings, LetsMT.MTProvider.LocalLetsMTWebService.MetadataField[] metadata) {
            this.fileName = fileName;
            this.content = content;
            this.systemID = systemID;
            this.ignoreWarnings = ignoreWarnings;
            this.metadata = metadata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDocTranslationResponse", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class CreateDocTranslationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        public string CreateDocTranslationResult;
        
        public CreateDocTranslationResponse() {
        }
        
        public CreateDocTranslationResponse(string CreateDocTranslationResult) {
            this.CreateDocTranslationResult = CreateDocTranslationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocTranslation", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class GetDocTranslationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        public string docID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=1)]
        public string filename;
        
        public GetDocTranslationRequest() {
        }
        
        public GetDocTranslationRequest(string docID, string filename) {
            this.docID = docID;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocTranslationResponse", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class GetDocTranslationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetDocTranslationResult;
        
        public GetDocTranslationResponse() {
        }
        
        public GetDocTranslationResponse(byte[] GetDocTranslationResult) {
            this.GetDocTranslationResult = GetDocTranslationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TranslationWebServiceSoapChannel : LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslationWebServiceSoapClient : System.ServiceModel.ClientBase<LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap>, LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap {
        
        public TranslationWebServiceSoapClient() {
        }
        
        public TranslationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Translate(string appID, string systemID, string text, string options) {
            return base.Channel.Translate(appID, systemID, text, options);
        }
        
        public string[] TranslateArray(string appID, string systemID, string[] textArray, string options) {
            return base.Channel.TranslateArray(appID, systemID, textArray, options);
        }
        
        public string DetectLanguage(string appID, string text, string[] candidateList) {
            return base.Channel.DetectLanguage(appID, text, candidateList);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.LocalLetsMTWebService.BreakSentencesResponse LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap.BreakSentences(LetsMT.MTProvider.LocalLetsMTWebService.BreakSentencesRequest request) {
            return base.Channel.BreakSentences(request);
        }
        
        public LetsMT.MTProvider.LocalLetsMTWebService.SentenceBoundary[] BreakSentences(string appID, string language, string text, string options) {
            LetsMT.MTProvider.LocalLetsMTWebService.BreakSentencesRequest inValue = new LetsMT.MTProvider.LocalLetsMTWebService.BreakSentencesRequest();
            inValue.appID = appID;
            inValue.language = language;
            inValue.text = text;
            inValue.options = options;
            LetsMT.MTProvider.LocalLetsMTWebService.BreakSentencesResponse retVal = ((LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap)(this)).BreakSentences(inValue);
            return retVal.BreakSentencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.LocalLetsMTWebService.GetSystemListResponse LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap.GetSystemList(LetsMT.MTProvider.LocalLetsMTWebService.GetSystemListRequest request) {
            return base.Channel.GetSystemList(request);
        }
        
        public LetsMT.MTProvider.LocalLetsMTWebService.MTSystem[] GetSystemList(string appID, string uiLanguageID) {
            LetsMT.MTProvider.LocalLetsMTWebService.GetSystemListRequest inValue = new LetsMT.MTProvider.LocalLetsMTWebService.GetSystemListRequest();
            inValue.appID = appID;
            inValue.uiLanguageID = uiLanguageID;
            LetsMT.MTProvider.LocalLetsMTWebService.GetSystemListResponse retVal = ((LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap)(this)).GetSystemList(inValue);
            return retVal.GetSystemListResult;
        }
        
        public System.Xml.XmlNode GetUserInfo(string appID) {
            return base.Channel.GetUserInfo(appID);
        }
        
        public void UpdateTranslation(string appID, string systemID, string text, string translation, string options) {
            base.Channel.UpdateTranslation(appID, systemID, text, translation, options);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.LocalLetsMTWebService.CreateDocTranslationResponse LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap.CreateDocTranslation(LetsMT.MTProvider.LocalLetsMTWebService.CreateDocTranslationRequest request) {
            return base.Channel.CreateDocTranslation(request);
        }
        
        public string CreateDocTranslation(string fileName, byte[] content, string systemID, bool ignoreWarnings, LetsMT.MTProvider.LocalLetsMTWebService.MetadataField[] metadata) {
            LetsMT.MTProvider.LocalLetsMTWebService.CreateDocTranslationRequest inValue = new LetsMT.MTProvider.LocalLetsMTWebService.CreateDocTranslationRequest();
            inValue.fileName = fileName;
            inValue.content = content;
            inValue.systemID = systemID;
            inValue.ignoreWarnings = ignoreWarnings;
            inValue.metadata = metadata;
            LetsMT.MTProvider.LocalLetsMTWebService.CreateDocTranslationResponse retVal = ((LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap)(this)).CreateDocTranslation(inValue);
            return retVal.CreateDocTranslationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.LocalLetsMTWebService.GetDocTranslationResponse LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap.GetDocTranslation(LetsMT.MTProvider.LocalLetsMTWebService.GetDocTranslationRequest request) {
            return base.Channel.GetDocTranslation(request);
        }
        
        public byte[] GetDocTranslation(string docID, string filename) {
            LetsMT.MTProvider.LocalLetsMTWebService.GetDocTranslationRequest inValue = new LetsMT.MTProvider.LocalLetsMTWebService.GetDocTranslationRequest();
            inValue.docID = docID;
            inValue.filename = filename;
            LetsMT.MTProvider.LocalLetsMTWebService.GetDocTranslationResponse retVal = ((LetsMT.MTProvider.LocalLetsMTWebService.TranslationWebServiceSoap)(this)).GetDocTranslation(inValue);
            return retVal.GetDocTranslationResult;
        }
        
        public System.Xml.XmlNode GetDoc(string docId) {
            return base.Channel.GetDoc(docId);
        }
        
        public void RemoveDoc(string docID) {
            base.Channel.RemoveDoc(docID);
        }
    }
}
