//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsMT.MTProvider.LetsMTWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.letsmt.eu/translationAPI", ConfigurationName="LetsMTWebService.TranslationWebServiceSoap")]
    public interface TranslationWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/Translate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Translate(string appID, string systemID, string text, string options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/TranslateArray", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] TranslateArray(string appID, string systemID, string[] textArray, string options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/DetectLanguage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DetectLanguage(string appID, string text, string[] candidateList);
        
        // CODEGEN: Parameter 'BreakSentencesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/BreakSentences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LetsMT.MTProvider.LetsMTWebService.BreakSentencesResponse BreakSentences(LetsMT.MTProvider.LetsMTWebService.BreakSentencesRequest request);
        
        // CODEGEN: Parameter 'GetSystemListResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.letsmt.eu/translationAPI/GetSystemList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LetsMT.MTProvider.LetsMTWebService.GetSystemListResponse GetSystemList(LetsMT.MTProvider.LetsMTWebService.GetSystemListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class SentenceBoundary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int startField;
        
        private int lengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class ObjectProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class LangText : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private LangText nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LangText Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.letsmt.eu/translationAPI")]
    public partial class MTSystem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private Language srcLanguageField;
        
        private Language trgLanguageField;
        
        private string domainField;
        
        private LangText titleField;
        
        private LangText descriptionField;
        
        private ObjectProperty[] metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Language SrcLanguage {
            get {
                return this.srcLanguageField;
            }
            set {
                this.srcLanguageField = value;
                this.RaisePropertyChanged("SrcLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Language TrgLanguage {
            get {
                return this.trgLanguageField;
            }
            set {
                this.trgLanguageField = value;
                this.RaisePropertyChanged("TrgLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("Domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public LangText Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public LangText Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
        public ObjectProperty[] Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BreakSentences", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class BreakSentencesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        public string appID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=1)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=2)]
        public string text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=3)]
        public string options;
        
        public BreakSentencesRequest() {
        }
        
        public BreakSentencesRequest(string appID, string language, string text, string options) {
            this.appID = appID;
            this.language = language;
            this.text = text;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BreakSentencesResponse", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class BreakSentencesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sentence", IsNullable=false)]
        public SentenceBoundary[] BreakSentencesResult;
        
        public BreakSentencesResponse() {
        }
        
        public BreakSentencesResponse(SentenceBoundary[] BreakSentencesResult) {
            this.BreakSentencesResult = BreakSentencesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSystemList", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class GetSystemListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        public string appID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=1)]
        public string uiLanguageID;
        
        public GetSystemListRequest() {
        }
        
        public GetSystemListRequest(string appID, string uiLanguageID) {
            this.appID = appID;
            this.uiLanguageID = uiLanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSystemListResponse", WrapperNamespace="http://www.letsmt.eu/translationAPI", IsWrapped=true)]
    public partial class GetSystemListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.letsmt.eu/translationAPI", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("System", IsNullable=false)]
        public MTSystem[] GetSystemListResult;
        
        public GetSystemListResponse() {
        }
        
        public GetSystemListResponse(MTSystem[] GetSystemListResult) {
            this.GetSystemListResult = GetSystemListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TranslationWebServiceSoapChannel : LetsMT.MTProvider.LetsMTWebService.TranslationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslationWebServiceSoapClient : System.ServiceModel.ClientBase<LetsMT.MTProvider.LetsMTWebService.TranslationWebServiceSoap>, LetsMT.MTProvider.LetsMTWebService.TranslationWebServiceSoap {
        
        public TranslationWebServiceSoapClient() {
        }
        
        public TranslationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Translate(string appID, string systemID, string text, string options) {
            return base.Channel.Translate(appID, systemID, text, options);
        }
        
        public string[] TranslateArray(string appID, string systemID, string[] textArray, string options) {
            return base.Channel.TranslateArray(appID, systemID, textArray, options);
        }
        
        public string DetectLanguage(string appID, string text, string[] candidateList) {
            return base.Channel.DetectLanguage(appID, text, candidateList);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.LetsMTWebService.BreakSentencesResponse LetsMT.MTProvider.LetsMTWebService.TranslationWebServiceSoap.BreakSentences(LetsMT.MTProvider.LetsMTWebService.BreakSentencesRequest request) {
            return base.Channel.BreakSentences(request);
        }
        
        public SentenceBoundary[] BreakSentences(string appID, string language, string text, string options) {
            LetsMT.MTProvider.LetsMTWebService.BreakSentencesRequest inValue = new LetsMT.MTProvider.LetsMTWebService.BreakSentencesRequest();
            inValue.appID = appID;
            inValue.language = language;
            inValue.text = text;
            inValue.options = options;
            LetsMT.MTProvider.LetsMTWebService.BreakSentencesResponse retVal = ((LetsMT.MTProvider.LetsMTWebService.TranslationWebServiceSoap)(this)).BreakSentences(inValue);
            return retVal.BreakSentencesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LetsMT.MTProvider.LetsMTWebService.GetSystemListResponse LetsMT.MTProvider.LetsMTWebService.TranslationWebServiceSoap.GetSystemList(LetsMT.MTProvider.LetsMTWebService.GetSystemListRequest request) {
            return base.Channel.GetSystemList(request);
        }
        
        public MTSystem[] GetSystemList(string appID, string uiLanguageID) {
            LetsMT.MTProvider.LetsMTWebService.GetSystemListRequest inValue = new LetsMT.MTProvider.LetsMTWebService.GetSystemListRequest();
            inValue.appID = appID;
            inValue.uiLanguageID = uiLanguageID;
            LetsMT.MTProvider.LetsMTWebService.GetSystemListResponse retVal = ((LetsMT.MTProvider.LetsMTWebService.TranslationWebServiceSoap)(this)).GetSystemList(inValue);
            return retVal.GetSystemListResult;
        }
    }
}
